## SPDX-License-Identifier: BSD-3-Clause
## Copyright (C) 2019 Mike Miller
##
## .travis.yml - Travis CI configuration for octave-travis-ci-example

dist: xenial
language: generic

services:
- docker

env:
- OCTAVE_VERSION=4.2
- OCTAVE_VERSION=4.4
- OCTAVE_VERSION=5

before_install:
- docker pull mtmiller/octave:${OCTAVE_VERSION}
- docker run mtmiller/octave:${OCTAVE_VERSION} octave --version

script:
- docker run --volume=${PWD}:/example:ro mtmiller/octave:${OCTAVE_VERSION} octave --path /example --eval "hello"
